<?php

function datapipe_menu() {
  $item['quipu_data_pipe/%/%/%/%'] = array(
          'type' => MENU_CALLBACK,
          'page callback' => 'datapipe_sorter',
	  'page arguments' => array(1,2,3,4),
	  'access arguments' => array('access content'),
	  'delivery callback' => 'drupal_json_output',
  );

  return $item;
};

function datapipe_sorter($mode, $name, $email, $url) {
  header('Access-Control-Allow-Origin: *');
  switch ($mode) {
    case ('listen_count'):
      $count = update_listen_count();
      return $count;
      break;
    case ('new_recording'):
/*      $person = array(
        'name' => $name,
	'email' => $email,
	'url' => $url,
      );
      $result = vsprintf('The recording by %s has been added with the email %s. Their link is %s', $person); */
      $result = save_recording($name, $email, $url);
      return $result;
      break;
  }; 
};

function update_listen_count() {
  $filename = "public://output/listen_count.txt";
  $f = fopen($filename, "r");
  $contents = fread($f, filesize($filename));
  $current_count = trim($contents, "\n");
  $new_count = (String)($current_count + 1);
  fclose($f);
  $f = fopen($filename, "w");
  $result = fwrite($f, $new_count);
  fclose($f);
  return $result;
};

function save_recording($name, $email, $url) {
  $filename = "public://output/recording.txt";
  $f = fopen($filename, "w");
  $contents = "Name:".$name."\nEmail:".$email."\nUrl:".$url;
  $result = fwrite($f, $contents);
  fclose($f);
  return $result;
};